version: '3'
services:

  jupyter:
    image: predictability-crawler
    build: 
      context: docker/
    volumes:
      - ./work/:/home/jovyan/work/
      - julia:/opt/julia/
    ports:
      - 8888:8888
    environment:
     - JULIA_NUM_THREADS=100
    #  - GRANT_SUDO=yes
     - JUPYTER_ENABLE_LAB=yes
     - COLUMNS:20
    # user: root


volumes:
  julia:
