version: '3'
services:

  jupyter:
    image: predictability-crawler
    build: 
      context: work/
      dockerfile: ../Dockerfile
    volumes:
      - ./work/:/home/jovyan/work/
      - ./data/:/home/jovyan/work/data/
    ports:
      - 8888:8888
    environment:
     - JULIA_NUM_THREADS=100
     - NO_BROWSER=yes
     - JUPYTER_ENABLE_LAB=yes
     - COLUMNS:20
